#!/bin/bash
trap 'die' EXIT
trap 'exit $?' INT TERM QUIT ABRT

function die
{
	if ! ((trapped)); then
		ret=$?
		trap ':' INT TERM QUIT ABRT EXIT
	fi
	(( ret == 0 && !trapped ))  || printf '\n'
	((trapped)) || export trapped=1
	if pgrep -xP "$$" &> /dev/null; then
		printf '\r -> Terminating threads.   \b\b\b'
		pkill -xP "$$"
		pwait -xP "$$"
	fi

	# TODO: Add your other cleanups here.
	printf ' -> Cleaning up.\n'
	exit $ret
}

for ((i = 0; i < 100; i++)); do
	((jobs++))

	# TODO: Do your own job here.
	sleep $((i % 5)) &

	until ((jobs < ${MAXJOBS:-5})); do
		jobs=$(jobs -r -p | wc -l)
		printf '\33[2K\r -> Completed tasks %d/%d' "$((i - jobs))" "100"
	done
done
while ((jobs > 0)); do
	jobs=$(jobs -r -p | wc -l)
	printf '\33[2K\r -> Completed tasks %d/%d' "$((100 - jobs))" "100"
done
echo

